// Firestore Schema Reference for Reflection App

/**
 * users (collection)
 *   - {userId} (document)
 *     - displayName: string (optional, user's display name)
 *     - email: string (optional, user's email address)
 *     - createdAt: Timestamp (optional, account creation date)
 *     - chatHistory (subcollection)
 *       - {chatId} (document)
 *         - title: string (title of the chat session)
 *         - lastMessage: string (text of the last message in the chat)
 *         - chatId: string (ID of the chat)
 *         - createdAt: Timestamp (when the chat was created)
 *         - updatedAt: Timestamp (last update to the chat)
 *         - messages (subcollection)
 *           - {messageId} (document)
 *             - role: string ('user' | 'assistant')
 *             - content: string (content of the message)
 *             - createdAt: Timestamp (when the message was created)
 *     - reflections (subcollection)
 *       - {reflectionId} (document)
 *         - title: string (e.g., "Reflection - May 17, 2025")
 *         - date: Timestamp (specific date of the reflection)
 *         - createdAt: Timestamp (when the reflection was created)
 *         - updatedAt: Timestamp (last update to the reflection)
 *         - lastEntryText: string (text of the most recent entry)
 *         - status: string ('in-progress' | 'completed')
 *         - entries (subcollection)
 *           - {entryId} (document)
 *             - text: string (content of the entry)
 *             - sender: string ('user' | 'ai' | 'system')
 *             - timestamp: Timestamp (when the entry was created)
 *             - type: string (optional, e.g., 'prompt', 'user_response')
 *             - metadata: map (optional, additional structured data)
 */
